---
- name: Deploy Maven Artifact
  hosts: web
  become: yes
  gather_facts: no

  tasks:
   - name: Copy JAR file
     copy:
      src: /var/lib/jenkins/workspace/prg8/my-Application/maven-example/target/maven-example-1.0-SNAPSHOT.jar
      dest: /home/jenkins/maven-example-1.0-SNAPSHOT.jar
      remote_src: true
      mode: '0755'
 
